version: '3.8'

services:
  influxdb:
    image: influxdb:2  # Or use InfluxDB 2.x if preferred
    volumes:
      - influxdb_data:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=logs  # Pre-creates your logs database
      - INFLUXDB_HTTP_AUTH_ENABLED=true  # Enable authentication
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER:-admin}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD:-adminpassword}
      - INFLUXDB_USER=${INFLUXDB_USER:-odyuser}
      - INFLUXDB_USER_PASSWORD=${INFLUXDB_USER_PASSWORD:-odypassword}
    ports:
      - "8086:8086"  # HTTP API port
      - "8083:8083"
    deploy:
      replicas: 1  # For InfluxDB, typically start with a single instance
      placement:
        constraints:
          - node.role == manager  # Run on manager node for persistence
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    healthcheck:
      test: ["CMD", "influx", "-execute", "SHOW DATABASES"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - influxdb_network

volumes:
  influxdb_data:
    driver: local

networks:
  influxdb_network:
    driver: overlay
    attachable: true